### ISSUE TITLE
3.1 - Plablaster's "Playblaster Render" button not working.

### ISSUE THREAD

**Issue by joshua-whitney** [samytichadou/Playblaster#2]
![image](https://user-images.githubusercontent.com/41597293/159798898-57d065cb-ac58-4158-a209-5e4c1aebcb9e.png)

**Comment by samytichadou** [comment]
sorry for late answer, this happens when something goes wrong in a playblast, there is a `is_rendering` property, which seems to have stay true.
You can fix that by going to the settings, toggling on the `debug `checkbox, then toggling off the `is_rendering`

Another reason this button could be grayed out is the blend is not saved (i see it is not your case with the screenshot, but just in case :) )

You should know this only applies with v1 of the addon, i'm currently working on a v2 with a lot more functions, but no background render (too much instable and not really compatible with opengl render, cheaper but needing a context)
v2 is available in its branch, and more stable than master where i did some experiments for the production i'm working on.

Cheers !
